debug: true
business_id: ''

auth:
  username: ''
  password: ''

api:
  domain: ''
  url: 'https://{api.domain}.manager.io/'

services:
  lob:
    live_token: ''
    test_token: ''
  sendgrid:
    live_token: ''

resources:
  # root resources
  bank: ''
  employee: ''
  invoice: ''
  payslip: ''

  # payroll accounts
  earnings: ''
  federal_deduction: ''
  medicare_deduction: ''
  employer_medicare: ''

custom_fields:
  invoice: ''
